server:
  servlet:
  port: 46778
  #1、 一定不要使用kill -9 操作，使用kill -2 来关闭容器。这样才会触发java内部ShutdownHook操作，kill -9不会触发ShutdownHook。
  #2、可以使用端点监控 POST 请求 /actuator/shutdown 来执行优雅关机。
  shutdown: graceful #开启优雅停机
  tomcat:
    # 参数中允许未编码的特殊字符
    relaxed-query-chars: <,>,[,\,],^,`,{,|,}
    # 请求URL中允许未编码的特殊字符
    relaxed-path-chars: <,>,[,\,],^,`,{,|,}

spring:
  mvc:
    # 前端参数格式化
    format:
      # String格式化日期
      date: yyyy-MM-dd HH:mm:ss
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://172.19.60.60:30696/mediinfo-lyra-authserver
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@172.19.80.161:1521:orcl
    username: LYRA_HIS
    password: LYRA_HIS
    multiple:
#      datasourcesjzx:
#        driver-class-name: org.postgresql.Driver
#        url: jdbc:postgresql://172.19.80.171:5432/lyra_his?currentSchema=grus_sc
#        username: lyra_his
#        password: lyra_his
#      datasourcebr:
#        driver-class-name: org.postgresql.Driver
#        url: jdbc:postgresql://172.19.80.171:5432/lyra_his?currentSchema=vela_br
#        username: lyra_his
#        password: lyra_his
      datasourcesjzx:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://172.19.60.142:5432/lyradb?currentSchema=grus_sc
        username: grus_sc
        password: grus_sc2023
      datasourcebr:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://172.19.60.136:5432/lyradb?currentSchema=vela_br
        username: vela_br
        password: vela_br2023
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  cache:
    type: redis
    redis:
      key-prefix: "mediinfo:"  #前缀
      time-to-live: 3600000   #缓存有效期，毫秒为单位
#  data:
#    redis:
#      database: 9
#      host: 172.19.33.31
#      lettuce:
#        pool:
#          max-active: 8
#          max-idle: 8
#          max-wait: -1
#          min-idle: 0
#      password: 'mediinfo@redis'
#      port: 6379
  data:
    redis:
      sentinel:
        master: mymaster
        nodes: 172.19.60.31:26379,172.19.60.32:26379,172.19.60.33:26379
      password: 'Mediinfo069'
  lifecycle:
    timeout-per-shutdown-phase: 30s
mediinfo:
  remote:
    urls:
      mediinfo-grus-huanzhe-query: "http://172.19.60.60:30696"
      # mediinfo-lyra-gongyong: "http://localhost:31004"
      mediinfo-lyra-gongyong: "http://172.19.60.60:30696"
      mediinfo-lyra-dizuo: "http://172.19.60.60:30696"
      mediinfo-grus-linchuang-query: "http://172.19.60.60:30696"
      mediinfo-grus-gongwei-query: "http://172.19.60.60:30696"
      mediinfo-lyra-nengli: "http://172.19.60.60:30696"
  sequence:
    provider: redis
  string-generator:
    provider: snowflake
    snowflake:
      workid: 1
  zhparser:
    state: 0  #全文检索状态 0关闭 1开启
logging:
  level:
    root: info

