server:
  #todo 暂时添加路径用于集群中swagger的访问
  servlet:
    context-path: /mediinfo-grus-shujuzx
  port: 80
  #1、 一定不要使用kill -9 操作，使用kill -2 来关闭容器。这样才会触发java内部ShutdownHook操作，kill -9不会触发ShutdownHook。
  #2、可以使用端点监控 POST 请求 /actuator/shutdown 来执行优雅关机。
  shutdown: graceful #开启优雅停机
  tomcat:
    # 参数中允许未编码的特殊字符
    relaxed-query-chars: <,>,[,\,],^,`,{,|,}
    # 请求URL中允许未编码的特殊字符
    relaxed-path-chars: <,>,[,\,],^,`,{,|,}
spring:
  cache:
    type: redis  # 配置缓存类型为Redis
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://mediinfo-lyra-authserver/mediinfo-lyra-authserver
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@172.19.80.161:1521:orcl
    username: LYRA_HIS
    password: LYRA_HIS
    multiple:
      datasourcesjzx:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://172.19.80.171:5432/lyra_his?currentSchema=grus_sc
        username: lyra_his
        password: lyra_his
      datasourcebr:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://172.19.80.171:5432/lyra_his?currentSchema=vela_br
        username: lyra_his
        password: lyra_his
  jpa:
    properties:
      hibernate:
        #根据类型可以生成特定的sql,https://docs.jboss.org/hibernate/orm/6.1/javadocs/org/hibernate/dialect/package-summary.html
        dialect: org.hibernate.dialect.PostgreSQLDialect
    #打印sql日志
    #show-sql: true
  data:
    redis:
      database: 9
      host: 172.19.33.31
      lettuce:
        pool:
          # 连接池最大连接数（使用负值表示没有限制） 默认 8
          max-active: 8
          # 连接池中的最大空闲连接 默认 8
          max-idle: 8
          # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
          max-wait: -1
          # 连接池中的最小空闲连接 默认 0
          min-idle: 0
      password: 'mediinfo@redis'
      port: 6379
  lifecycle:
    timeout-per-shutdown-phase: 30s #设置缓冲时间 默认30s
  application:
    name:
  profiles:
    active: ${ASPNETCORE_ENVIRONMENT}
management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    tags:
      application: ${spring.application.name}
logging:
  config: classpath:logback-spring.xml
  level:
    root: info
    #打印sql参数
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.hibernate.type.descriptor.sql.BasicExtractor: trace
mediinfo:
  remote:
    urls:
      mediinfo-grus-huanzhe-query: "http://mediinfo-grus-huanzhe-query"
      mediinfo-lyra-gongyong: "http://mediinfo-lyra-gongyong"
      mediinfo-lyra-dizuo: "http://mediinfo-lyra-dizuo"
      mediinfo-grus-linchuang-query: "http://mediinfo-grus-linchuang-query"
      mediinfo-grus-gongwei-query: "http://mediinfo-grus-gongwei-query"
  sequence:
    provider: redis
  string-generator:
    provider: snowflake
    snowflake:
      workid: 1
  zhparser:
    state: 0  #全文检索状态 0关闭 1开启

