server:
  servlet:
  port: 46203
  #1、 一定不要使用kill -9 操作，使用kill -2 来关闭容器。这样才会触发java内部ShutdownHook操作，kill -9不会触发ShutdownHook。
  #2、可以使用端点监控 POST 请求 /actuator/shutdown 来执行优雅关机。
  shutdown: graceful #开启优雅停机
  tomcat:
    # 参数中允许未编码的特殊字符
    relaxed-query-chars: <,>,[,\,],^,`,{,|,}
    # 请求URL中允许未编码的特殊字符
    relaxed-path-chars: <,>,[,\,],^,`,{,|,}

spring:
  mvc:
    # 前端参数格式化
    format:
      # String格式化日期
      date: yyyy-MM-dd HH:mm:ss
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://172.19.80.10:30003/mediinfo-lyra-authserver
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@172.19.80.161:1521:orcl
    username: LYRA_HIS
    password: LYRA_HIS
    multiple:
      datasourcesjzx:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://172.19.80.171:5432/lyra_his?currentSchema=grus_sc
        username: lyra_his
        password: lyra_his
      datasourcebr:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://172.19.80.171:5432/lyra_his?currentSchema=vela_br
        username: lyra_his
        password: lyra_his
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    cache:
      type: redis
      redis:
        key-prefix: "mediinfo:"  #前缀
        time-to-live: 3600000   #缓存有效期，毫秒为单位
  data:
    redis:
      database: 9
      host: 172.19.33.31
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          max-wait: -1
          min-idle: 0
      password: 'mediinfo@redis'
      port: 6379
  lifecycle:
    timeout-per-shutdown-phase: 30s
  application:
    name:
mediinfo:
  remote:
    urls:
      mediinfo-grus-huanzhe-query: "http://172.19.80.10:31003/mediinfo-grus-huanzhe-query"
  sequence:
    provider: redis
  string-generator:
    provider: snowflake
    snowflake:
      workid: 1
logging:
  level:
    root: info

